import assert from 'node:assert/strict';
import * as Cesium from 'cesium';
import {downloadedAreaSphere,fitDownloadedTileset} from '../src/tiles3d-camera.ts';
 const bounds=[116.458,39.906,116.462,39.910],sphere=downloadedAreaSphere(bounds);
 const center=Cesium.Cartographic.fromCartesian(sphere.center);
 assert(Math.abs(Cesium.Math.toDegrees(center.longitude)-116.460)<0.0001);
 assert(Math.abs(Cesium.Math.toDegrees(center.latitude)-39.908)<0.0001);
 assert(sphere.radius>200&&sphere.radius<500,'Local bounds must not use the global root radius');
 const calls=[];
 const viewer={camera:{viewBoundingSphere:(sphere,offset)=>calls.push({type:'bounds',sphere,offset}),lookAtTransform:()=>calls.push({type:'reset'})},scene:{requestRender:()=>calls.push({type:'render'})},zoomTo:(model,offset)=>calls.push({type:'model',model,offset})};
 const model={boundingSphere:{radius:6378137}};
 fitDownloadedTileset(viewer,model,bounds);
 assert.deepEqual(calls.map(c=>c.type),['bounds','reset','render']);
 assert(calls[0].offset.range<2000);assert(calls[0].offset.range>=1200);
 const initial=calls[0];calls.length=0;fitDownloadedTileset(viewer,model,bounds);
 assert.equal(calls[0].sphere.radius,initial.sphere.radius);assert.equal(calls[0].offset.range,initial.offset.range);
 calls.length=0;fitDownloadedTileset(viewer,model);
 assert.equal(calls[0].type,'model');assert.equal(calls[0].offset.range,6378137*3.2);
 for(const invalid of [null,[],[1,2,3],[1,2,3,1],[181,0,182,1],[1,2,1,3],[1,2,3,NaN]])assert.equal(downloadedAreaSphere(invalid),null);
 const dateline=downloadedAreaSphere([179.9,-0.1,-179.9,0.1]);assert(dateline.radius<20000,'Dateline bounds should remain local');
 console.log(JSON.stringify({pass:true,checks:['Beijing bounds override global root','initial fit and reset share target','unbounded model fallback','invalid bounds rejected','dateline bounds'],radius:sphere.radius,range:initial.offset.range}));
