// Real native discovery, persistent incremental boundary, and historical imagery download.
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const rpc=async(command,args={})=>{const r=await(await fetch('http://127.0.0.1:1421/rpc',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command,args})})).json();if(r.error)throw {command,tool:args.toolName??args.tool,...(typeof r.error==='object'?r.error:{message:r.error})};if(command!=='jobs_get')console.log(`${command}${args.toolName??args.tool?` ${args.toolName??args.tool}`:''}: complete`);return r.value;};
const conversationId=`wayback-${randomUUID()}`,workspace=resolve('../../artifacts/desktop-parity',conversationId);mkdirSync(workspace,{recursive:true});
await rpc('workspace_set',{conversationId,directory:workspace,permission:'fullAccess'});
const discovered=await rpc('source_creator_tools');assert(discovered.tools.some(t=>t.name==='wayback_changes'));
const versions=await rpc('source_creator_call',{toolName:'wayback_versions',arguments:{limit:1}});
const latest=versions.versions[0];assert(versions.total>1);assert.equal(typeof latest.source.urlTemplate,'string');
const oldestPage=await rpc('source_creator_call',{toolName:'wayback_versions',arguments:{offset:versions.total-1,limit:1}});
const oldest=oldestPage.versions[0],bounds=[116.395,39.895,116.405,39.905];
const metadata=await rpc('source_creator_call',{toolName:'wayback_metadata',arguments:{releaseId:latest.releaseId,bounds,zoom:16}});
assert(metadata.footprints.length>0);assert(metadata.footprints.every(f=>f.captureDate===null||/^\d{4}-\d{2}-\d{2}$/.test(f.captureDate)));
const changes=await rpc('test_boundary_tool',{conversationId,tool:'wayback_changes',arguments:{fromReleaseId:oldest.releaseId,toReleaseId:latest.releaseId,bounds,zoom:16}});
assert.equal(changes.found,true);assert.equal(typeof changes.boundaryId,'string');
const boundary=await rpc('boundaries_get',{conversationId,boundaryId:changes.boundaryId});assert(boundary.polygonCount>0);
for(let i=0;i<4;i++)assert(Math.abs(boundary.bounds[i]-bounds[i])<0.011,'Incremental boundary escaped the requested region');
const sourceId=`wayback-native-${latest.releaseId}-${randomUUID().slice(0,8)}`;
const source=await rpc('test_source_configure',{...latest.source,id:sourceId});assert(source.saved,JSON.stringify(source));
const planned=await rpc('test_imagery_plan',{conversationId,executionId:`wayback-native:${randomUUID()}`,arguments:{sourceId,boundaryId:changes.boundaryId,zoom:15,outputFormats:['geotiff'],exportOptions:{compression:'deflate'}}});
assert.equal(planned.errors.length,0,JSON.stringify(planned.errors));const stored=planned.plans[0].stored;
assert(stored.plan.spec.boundary);assert.equal(stored.plan.spec.sourceId,sourceId);
const job=await rpc('jobs_start_auto',{planId:stored.planId,conversationId,idempotencyKey:`wayback-native:${randomUUID()}`});
let status;const deadline=Date.now()+120000;
do {status=await rpc('jobs_get',{jobId:job.jobId});if(['completed','failed','partial','cancelled'].includes(status.state))break;await new Promise(r=>setTimeout(r,250));}while(Date.now()<deadline);
assert.equal(status.state,'completed',JSON.stringify(status));const manifest=await rpc('artifacts_inspect',{jobId:job.jobId});assert.equal(manifest.quality.status,'complete');
const raster=await rpc('test_native_raster',{jobId:job.jobId});assert(raster.samples.some(v=>v>0));
const report={pass:true,checkedAt:new Date().toISOString(),conversationId,workspace,versions,oldest,metadata,changes,boundary,stored,job,manifest,raster};
writeFileSync(resolve('../../docs/implementation/evidence/wayback-native-2026-10-02.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({pass:true,versions:versions.total,releaseDate:latest.releaseDate,captureDates:metadata.footprints.map(f=>f.captureDate),jobId:job.jobId,tiles:stored.plan.totalTiles}));
