import { getLocale, t, localize } from "./i18n";
// i18n: presentation strings migrated
import {useEffect,useRef,useState} from "react";
import * as Select from "@radix-ui/react-select";
import {api,errorMessage,type AiScheduleOverview,type AiScheduledRun} from "./api";
import {Button} from "./components/motion/button/base";
import {ChevronDown,Plus} from "./icons";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
const initial=():AiScheduleOverview=>({schedules:[],runs:[],windowRequired:false});
const states:Record<string,string>={queued:"排队中",running:"执行中",waiting_input:"需要输入",interrupted:"已中断",succeeded:"已完成",failed:"失败",cancelled:"已取消"};
const date=(value:string)=>new Date(value).toLocaleString(getLocale(),{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false});
const future=()=>{const value=new Date(Date.now()+5*60000);return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function AiSchedulePanel({conversationId,createOnly=false,scheduleId,onChanged}:{conversationId:string;createOnly?:boolean;scheduleId?:string;onChanged?:()=>void}){
  const currentConversation=useRef(conversationId);currentConversation.current=conversationId;
  const [data,setData]=useState(initial),[editing,setEditing]=useState(createOnly),[name,setName]=useState(""),[prompt,setPrompt]=useState(""),[time,setTime]=useState(future),[repeat,setRepeat]=useState("once"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [selected,setSelected]=useState<{run:AiScheduledRun;events:Record<string,unknown>[]} |null>(null);
  useEffect(()=>{let disposed=false,loading=false;setData(initial());setSelected(null);setError("");setEditing(createOnly);setBusy(false);if(createOnly)return;const refresh=async()=>{if(loading)return;loading=true;try{const result=await api.aiSchedulesList(conversationId);if(!disposed)setData(result);}catch(cause){if(!disposed)setError(errorMessage(cause));}finally{loading=false;}};void refresh();const timer=setInterval(()=>void refresh(),3000);return()=>{disposed=true;clearInterval(timer);};},[conversationId,createOnly]);
  const action=async(fn:()=>Promise<unknown>,changed=true)=>{setBusy(true);setError("");try{await fn();if(!createOnly){const fresh=await api.aiSchedulesList(conversationId);if(currentConversation.current===conversationId)setData(fresh);}if(currentConversation.current===conversationId&&changed)onChanged?.();}catch(cause){if(currentConversation.current===conversationId)setError(errorMessage(cause));}finally{if(currentConversation.current===conversationId)setBusy(false);}};
  const open=async(run:AiScheduledRun)=>action(async()=>{const result=await api.aiSchedulesRunEvents(run.runId);if(currentConversation.current===conversationId)setSelected(result);},false);
  return <section className="schedule-section ai-schedule-section">{!createOnly&&!scheduleId&&<><div className="schedule-heading"><h4>{t("AI 定时执行")}{data.schedules.length>0&&<span>{data.schedules.length}</span>}</h4><Button variant="ghost" size="sm" disabled={busy} onClick={()=>{setEditing(!editing);setTime(future());}}><Plus size={14}/>{editing?t("收起"):t("新建")}</Button></div>
    <p className="schedule-hint">{t("按指令调用 AI 和本机工具，关闭窗口后继续执行。重开后台会补跑一次到期任务，结果保存在运行记录中。")}</p></>}
    {editing&&<form className="schedule-form" onSubmit={event=>{event.preventDefault();void action(async()=>{await api.aiSchedulesCreate(conversationId,name,prompt,new Date(time).toISOString(),repeat==="once"?null:Number(repeat));setEditing(false);setName("");setPrompt("");});}}>
      <label>{t("名称")}<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>
      <label>{t("执行指令")}<textarea required rows={4} maxLength={60000} value={prompt} placeholder={t("例如：每天检查工作区里的数据，汇总新增文件及范围")} onChange={e=>setPrompt(e.target.value)}/></label>
      <label>{t("开始时间")}<input required type="datetime-local" value={time} onChange={e=>setTime(e.target.value)}/></label>
      <Select.Root value={repeat} onValueChange={setRepeat}><Select.Trigger className="select-trigger" aria-label={t("AI 重复频率")}><Select.Value/><Select.Icon><ChevronDown size={15}/></Select.Icon></Select.Trigger><Select.Portal><Select.Content className="select-content" position="popper" sideOffset={6}><Select.Viewport>{[{value:"once",label:"仅一次"},{value:"3600",label:"每小时"},{value:"86400",label:"每天"},{value:"604800",label:"每周"}].map(v=><Select.Item className="select-item" value={v.value} key={v.value}><Select.ItemText>{t(v.label)}</Select.ItemText></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>
      <p>{t("沿用当前工作区权限。需要输入、确认或地图视图时暂停本次执行；AI 用量正常计入账号。")}</p><Button type="submit" size="sm" disabled={busy}>{busy?t("保存中…"):t("保存 AI 定时任务")}</Button>
    </form>}
    {!createOnly&&<div className="schedule-list">{data.schedules.filter(schedule=>!scheduleId||schedule.scheduleId===scheduleId).map(schedule=>{const runs=data.runs.filter(run=>run.scheduleId===schedule.scheduleId),latest=runs[0];return <div className="schedule-item" key={schedule.scheduleId}><div className="schedule-item-caption"><strong>{schedule.name}</strong><Button variant="ghost" size="sm" disabled={busy} onClick={()=>void action(()=>api.aiSchedulesSetEnabled(schedule.scheduleId,!schedule.enabled,!schedule.enabled&&!schedule.repeatSeconds?new Date(Date.now()+300000).toISOString():undefined))}>{schedule.enabled?t("暂停"):t("启用")}</Button></div><p>{schedule.enabled?`${date(schedule.nextRunAt)} · ${schedule.repeatSeconds===86400?t("每天"):schedule.repeatSeconds===604800?t("每周"):schedule.repeatSeconds===3600?t("每小时"):schedule.repeatSeconds?t("每 {0} 秒",{0:schedule.repeatSeconds}):t("一次")}`:t("已停止后续触发")}</p><details className="ai-schedule-prompt"><summary>{t("执行指令")}</summary><p>{schedule.prompt}</p></details>
      {latest&&<div className="ai-run-controls"><Button variant="ghost" size="sm" className="schedule-run-row" onClick={()=>void open(latest)}><span>{date(latest.scheduledAt)} · {t(states[latest.state]??latest.state)}</span><span>{t("查看结果")}</span></Button>{["queued","running","waiting_input","interrupted"].includes(latest.state)&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void action(()=>api.aiSchedulesCancelRun(latest.runId))}>{t("取消本次")}</Button>}{["failed","waiting_input","interrupted"].includes(latest.state)&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>void action(()=>api.aiSchedulesRetryRun(latest.runId))}>{t("重试")}</Button>}</div>}
      {runs.length>1&&<details className="schedule-history"><summary>{t("运行记录 · ")}{runs.length}</summary>{runs.slice(1,10).map(run=><Button key={run.runId} variant="ghost" size="sm" className="schedule-run-row" onClick={()=>void open(run)}>{date(run.scheduledAt)} · {t(states[run.state]??run.state)}</Button>)}</details>}
    </div>;})}</div>}
    {selected&&<section className="ai-run-result"><div className="schedule-heading"><h4>{selected.run.name}</h4><Button variant="ghost" size="sm" disabled={busy} onClick={()=>void open(selected.run)}>{t("刷新")}</Button><Button variant="ghost" size="sm" onClick={()=>setSelected(null)}>{t("收起")}</Button></div><p className="schedule-hint">{date(selected.run.scheduledAt)} · {t(states[selected.run.state]??selected.run.state)}</p>{selected.run.result?.text&&<div className="geod-message-body"><ReactMarkdown remarkPlugins={[remarkGfm]}>{selected.run.result.text}</ReactMarkdown></div>} {selected.run.error&&<p className="warning-text">{selected.run.error.message}</p>}<details><summary>{t("执行详情 · ")}{selected.events.length} {t(" 项")}</summary><pre>{JSON.stringify(selected.events,null,2)}</pre></details></section>}
    {error&&<p role="alert" className="warning-text">{localize(error)}</p>}
  </section>;
}
